/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ApiGateway": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "AssetsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Dashboard": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "DelayedTaskStateMachine": {
      "arn": string
      "type": "sst.aws.StepFunctions"
    }
    "EmailTopic": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "JwtSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SendraDatabase": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "SendraRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "Subscription": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "TaskDeadLetterQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "TaskQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}