/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Dashboard": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "DelayedTaskStateMachine": {
      "arn": string
      "type": "sst.aws.StepFunctions"
    }
    "EmailTopic": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "PlunkMain": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "TaskDeadLetterQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "TaskQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}